### ISSUE TITLE
Nicer error message prompts

### ISSUE THREAD

**Issue by TheKevJames** [Calligre/attendee-web#103] opened 2017-03-24 21:27 UTC
I tried to post to twitter. I got this:

![image](https://cloud.githubusercontent.com/assets/3341822/24314263/1e723f7a-10b7-11e7-9c9c-8638445a3ca0.png)

**Comment by larajanecka** [comment] 2017-03-26 04:51
This is gonna be a massive hunt replace, assigning steven for now

**Comment by larajanecka** [comment] 2017-03-26 04:53
Duplicate of #49 So Imma close that one

**Closed as completed** 2017-10-18 03:22 UTC
Labels: bug, design
